name: update-gl-js

on: 
  workflow_dispatch:
  repository_dispatch:
    types: [release-maplibre-gl-js]

jobs:
  update-gl-js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: git config --global user.email "mail@example.com"
    - run: git config --global user.name "GitHub Action"
    - name: Prepare
      id: prepare
      run: |
        echo "::set-output name=version_tag::$(npm show maplibre-gl version)"
    - run: git checkout -b v${{ steps.prepare.outputs.version_tag }}
    - run: |
        git submodule update --init
        cd maplibre-gl-js
        git checkout main
        git pull
        cd ..
        git add -u
        git commit -m "Update MapLibre GL JS to v${{ steps.prepare.outputs.version_tag }}"
    - run: git push --set-upstream origin v${{ steps.prepare.outputs.version_tag }}
    - run: gh pr create --base main --fill
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
